name: Build F1 4.9

on:
  workflow_dispatch:
    inputs:

      kernel_source:
        description: 'Kernel Source Repository'
        required: true
        default: 'https://github.com/kyzuna28/kyy.git'
        type: string

      kernel_branch:
        description: 'Kernel Branch'
        required: true
        default: 'nse'
        type: string

      device:
        description: 'Device Codename'
        required: true
        default: 'beryllium'
        type: string

      defconfig:
        description: 'Defconfig File Path (Relative to arch/arm64/configs/)'
        required: true
        default: 'beryllium_defconfig'
        type: string

      compiler:
        description: 'Compiler'
        required: true
        default: 'neutron'
        type: choice
        options:
          - neutron
          - proton
          - lineage
          - aosp

      kernelsu:
        description: 'KernelSU'
        required: true
        default: 'resukisu'
        type: choice
        options:
          - resukisu
          - sukisu
          - next
          - xxksu
          - rsuntk
          - disable

      hook_method:
        description: 'Hook Method'
        required: true
        default: 'inline'
        type: choice
        options:
          - inline
          - manual
          - syscall
          - tracepoint

      enable_susfs:
        description: 'Enable SuSFS'
        required: true
        default: true
        type: boolean

      susfs_patch:
        description: 'SuSFS Patch'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - fixed patch
          - none

      susfs_folder_fixed:
        description: 'Fixed Patch Folder Name'
        required: false
        default: 'epwan'
        type: string

      susfs_patch_fixed:
        description: 'Fixed Patch File Name'
        required: false
        default: 'susfs_fixed'
        type: string

      merge_config:
        description: 'Use Merge Config'
        required: true
        default: false
        type: boolean

      merge_files:
        description: 'Merge Config Files Path (Relative to arch/arm64/configs/)'
        required: false
        default: 'vendor/xiaomi/mi845.config'
        type: string

      enable_rekernel:
        description: 'Enable Re:Kernel'
        required: true
        default: true
        type: boolean

      enable_droidspaces:
        description: 'Enable Droidspaces'
        required: true
        default: true
        type: boolean

      enable_baseband_guard:
        description: 'Enable Baseband Guard'
        required: true
        default: true
        type: boolean

      enable_kpm:
        description: 'Enable KPM'
        required: true
        default: false
        type: boolean

      ak3_repository:
        description: 'AnyKernel3 Repository'
        required: true
        default: 'https://github.com/osm0sis/AnyKernel3.git'
        type: string

      ak3_branch:
        description: 'AnyKernel3 Branch'
        required: true
        default: 'master'
        type: string

      upload_release:
        description: 'Upload Artifact'
        required: true
        default: true
        type: boolean

env:
  KERNEL_SOURCE: ${{ github.event.inputs.kernel_source }}
  KERNEL_BRANCH: ${{ github.event.inputs.kernel_branch }}
  DEVICE_CODENAME: ${{ github.event.inputs.device }}
  DEFCONFIG_NAME: ${{ github.event.inputs.defconfig }}
  
  COMPILER_CHOICE: ${{ github.event.inputs.compiler }}
  KERNELSU_AUTO_FORK: ${{ github.event.inputs.kernelsu }}
  HOOK_METHOD: ${{ github.event.inputs.hook_method }}
  SUSFS_PATCH_METHOD: ${{ github.event.inputs.susfs_patch }}
  SUSFS_FOLDER_FIXED: ${{ github.event.inputs.susfs_folder_fixed }}
  SUSFS_PATCH_FIXED: ${{ github.event.inputs.susfs_patch_fixed }}
  
  SUSFS_ENABLE: ${{ github.event.inputs.enable_susfs }}
  REKERNEL_ENABLE: ${{ github.event.inputs.enable_rekernel }}
  DROIDSPACES_ENABLE: ${{ github.event.inputs.enable_droidspaces }}
  BASEBAND_GUARD_ENABLE: ${{ github.event.inputs.enable_baseband_guard }}
  KPM_ENABLE: ${{ github.event.inputs.enable_kpm }}
  UPLOAD_RELEASE: ${{ github.event.inputs.upload_release }}
  
  BUILD_OTHER_CONFIG: ${{ github.event.inputs.merge_config }}
  MERGE_CONFIG_FILES: ${{ github.event.inputs.merge_files }}
  
  AK3_SOURCE: ${{ github.event.inputs.ak3_repository }}
  AK3_BRANCH: ${{ github.event.inputs.ak3_branch }}

  # -- STATIC ENV --
  DEVICE_NAME: "xiaomi-f1" 
  CUSTOM_CMDS: "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS: "LD=ld.lld"
  GCC_GNU: false
  GCC_64_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH: "android12L-release"
  GCC_32_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH: "android12L-release"
  DEFCONFIG_SOURCE: ""
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false
  KERNELSU_SOURCE: ""
  KERNELSU_BRANCH: ""
  KERNELSU_AUTO_GET: "true"
  BOOT_SOURCE: ""
  NEED_DTBO: false
  NEED_SAFE_DTBO: false
  ROM_TEXT: ""
  PYTHON_VERSION: "3"
  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"
  KERNELSU_METHOD: "shell"
  KERNELSU_SUS_PATCH: "false"
  PATCHES_SOURCE: "kyzuna28/Non-Gki-Build"
  PATCHES_BRANCH: "F1"
  KERNEL_PATCH: "false"
  KPM_INLINE: "false"
  KPM_KPATCH_NEXT: "false"
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux"
  BASEBAND_GUARD_BOOT: "false"
  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"
  BUILD_DEBUGGER: "false"
  SKIP_PATCH: "false"
  FREE_MORE_SPACE: "false"

jobs:
  build-kernel:
    name: ${{ github.event.inputs.device }} Kernel Build
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        if: ${{ github.event.inputs.enable_susfs == 'true' }}
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options & Merge Config Control
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          
          if [ "${{ github.event.inputs.merge_config }}" == "true" ] && [ -n "${{ github.event.inputs.merge_files }}" ]; then
            echo "[+] Merge Config is ENABLED."
            echo "[+] Base Defconfig Path: arch/arm64/configs/${{ github.event.inputs.defconfig }}"
            echo "[+] Merge Config Path: arch/arm64/configs/${{ github.event.inputs.merge_files }}"
          else
            echo "[-] Merge Config is DISABLED."
            echo "[-] Target Defconfig: arch/arm64/configs/${{ github.event.inputs.defconfig }}"
            
            # Mematikan variable merge secara paksa agar script builder utama melewatinya
            echo "BUILD_OTHER_CONFIG=false" >> $GITHUB_ENV
            echo "MERGE_CONFIG_FILES=" >> $GITHUB_ENV
          fi

      - name: 🧰 Patch Kernel of Re:Kernel
        if: ${{ github.event.inputs.enable_rekernel == 'true' }}
        uses: ./.github/workflows/patch-rekernel

      - name: 💿 Patch Kernel of Droidspaces
        if: ${{ github.event.inputs.enable_droidspaces == 'true' }}
        uses: ./.github/workflows/patch-droidspaces

      - name: 🔒 Patch Kernel of Baseband Guard
        if: ${{ github.event.inputs.enable_baseband_guard == 'true' }}
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        if: ${{ github.event.inputs.upload_release == 'true' }}
        uses: ./.github/workflows/upload-files
        
